name: "Deploy Preview Environment"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  trigger-preview:
    permissions:
      actions: write
      contents: read
      pull-requests: write
      statuses: write
    uses: opendata-swiss/opendata-swiss-cms-content/.github/workflows/preview.yaml@main
    secrets: inherit
