name: Trigger Harvesting showcases

on:
  push:
    branches:
      - main
    paths:
      - "showcases/**"

jobs:
  trigger:
    permissions:
      actions: write
      contents: read
      pull-requests: write
      statuses: write
    uses: opendata-swiss/opendata-swiss-cms-content/.github/workflows/trigger-showcase-harvesting.yaml@main
    secrets: inherit
